SELECT DISTINCT ?musician ?musicianLabel ?instrumentLabel
WHERE {
    ?musician (wdt:P106/wdt:P279*) wd:Q639669.
    ?musician wdt:P1303 ?instrument.
    FILTER (?instrument IN (wd:Q61285, wd:Q6607)).
    SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
}