SELECT ?item ?itemLabel ?date_of_birth ?date_of_death ?cause_of_deathLabel
WHERE {
    ?item (wdt:P106/wdt:P279*) wd:Q639669.
    ?item wdt:P569 ?date_of_birth.
    ?item wdt:P570 ?date_of_death.
    ?item wdt:P509 ?cause_of_death.
    SERVICE wikibase:label {
        bd:serviceParam wikibase:language "en".
    }
}
LIMIT 100