#defaultView:Graph
SELECT ?item ?itemLabel ?_influenced_by ?_influenced_byLabel
WHERE
{
  ?item wdt:P31 wd:Q9143.
  SERVICE wikibase:label { bd:serviceParam wikibase:language "en". }
  ?item wdt:P737 ?_influenced_by.
}