PREFIX wikibase: <http://wikiba.se/ontology#>
PREFIX wd: <http://www.wikidata.org/entity/>
PREFIX wdt: <http://www.wikidata.org/prop/direct/>

SELECT ?langid ?language WHERE {
    ?langid wdt:P31 wd:Q9143 .

    OPTIONAL {
        ?langid rdfs:label ?language filter (lang(?language) = "en") .
    }
}