SELECT subreddit, dayofweek, hourofday, num_with_min_score, total
FROM (
    SELECT
      DAYOFWEEK(STRING(created_utc)) as dayofweek,
      HOUR(STRING(created_utc)) as hourofday,
      SUM(score >= 1000) as num_with_min_score,
      SUM(num_with_min_score) OVER(PARTITION BY subreddit) total,
      subreddit,
    FROM [fh-bigquery:reddit_posts.full_corpus_201512]
    GROUP BY subreddit, dayofweek, hourofday
    ORDER BY subreddit, dayofweek, hourofday
)
WHERE total>70
ORDER BY total DESC, dayofweek, hourofday